version: '3'

services:
    brevetsapp:
        build: brevetsapp/
        command: python -u flask_brevets.py
        ports:
            - "7777:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    restapi:
        build: api/
        command: python -u api.py
        ports:
            - "7778:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    website:
        build: website/
        command: python -u website.py
        ports:
            - "7779:5000"
        depends_on:
            - restapi
        environment:
          BACKEND_ADDR: restapi
          BACKEND_PORT: 5000
    ourdb:
        image: mongo:latest
